name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e589999cb84f6af0590a3692ea2837f48e # v7.0.1
      - uses: actions/setup-node@8207627b5e406385d6b4a625f3c9eefaa57fb905 # v7.0.0
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm test
